Next
ccims/gropius-login-service pull request #2
Opened 2024-07-27 15:09 UTC by nk-coding

- remove username password flow
- add PKCE (required)
- use public/private key JWT signing/verification
- add GitHub/Jira cloud token strategy
- host frontend directly by login service
- add schema for strategy instance configuration
- add endpoint to read (admin) censored strategy instance configuration
- move to /auth root endpoint
- display error messages for failed login/register events
- make redirect URLs required

2024-07-29 09:08 UTC, spethso requested changes
Please double check the public and private key comment

2024-07-29 09:08 UTC, spethso commented on backend/.env.dev
Does it make sense to publish keys? I would assume this is not expected

2024-07-29 09:08 UTC, spethso commented on backend/src/api-internal/auth-redirect.middleware.ts
> +            ActiveLogin.LOGGED_IN_BUT_TOKEN_NOT_YET_RETRIVED + (state.secondToken ? 2 : 0)
What do the numbers mean? Would it make sense to change them to something clearer?

2024-07-29 13:09 UTC, nk-coding commented on backend/.env.dev
this is for the local dev setup
if we don't do this (at least in ccims/gropius), even when you want to have a local test instance, you would need to generate two ssl keys using e.g. openssl and then configure these using env variables
I mean we can get rid of them, however this will make getting started with Gropius more difficult

2024-07-29 15:03 UTC, spethso commented on backend/.env.dev
Okay, if there are no real issues arising by having the keys here, we can keep them

2024-07-29 15:06 UTC, nk-coding commented on backend/.env.dev
I mean it's an issue if you just deploy the testing version without changing any of the secrets
but the user admin with password admin is probably the bigger issue then anyways
for production, we provide a script which generates secure values automatically

2024-07-29 15:11 UTC, spethso approved these changes

2024-07-30 16:01 UTC, nk-coding commented on backend/src/api-internal/auth-redirect.middleware.ts
> +            ActiveLogin.LOGGED_IN_BUT_TOKEN_NOT_YET_RETRIVED + (state.secondToken ? 2 : 0)
added a comment with b95010079b5a03649440f7c32179d816f2a769d1

2024-08-02 08:18 UTC, spethso approved these changes

2024-08-04 07:24 UTC, merged